api:
  devolucao:
    dias: 5
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sec
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


